PersonnelRole Enum
MegaMek/mekhq pull request #2352
Opened 2021-01-08 04:21 UTC by Windchild292

This PR implements PersonnelRole as an Enum, a grouping of role-related bugfixes, and adds the basis of the Dependent Role. There will be more changes in future for this role, and there _may_ be bugs for it. However, I believe the bugs are minimal as part of the larger implementation and they will be fixed in the near future as I move to a full rollout of the dependent role alongside #1886.

To review:
0.47.X: Do not.
Post-0.48.0: The goal is for this to be merged in for 0.49.0.

State:

- [x] PersonnelRole Enum
- [x] Dependent Role Baseline
- [x] PersonnelRole Enum Migration
- [ ] PersonnelRole Enum-based Array Migration

2021-01-08 04:29 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/personnel/Person.java
>      public int getExperienceLevel(boolean secondary) {
I'm not certain the logic for this method should stay here or be moved to the PersonnelRole Enum given how much it relies on the latter, but the heavy reliance on Personnel is why I've kept it here.

2021-01-08 04:29 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/personnel/Person.java
> +    public boolean canPerformRole(PersonnelRole role) {
I'm not certain the logic for this method should stay here or be moved to the PersonnelRole Enum given how much it relies on the latter, but the heavy reliance on Personnel is why I've kept it here.

2021-01-08 04:29 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/personnel/Person.java
> +    public boolean hasSupportRole(boolean excludeUnmarketable) {
Key note for review: the boolean has been flipped, so anyone using the former value will be doing so incorrectly.

2021-04-22 02:24 UTC, NickAragua requested changes
Nothing major. No need to do anything with the ternary operator comments, they're only there to illustrate a point about relative readability of code to different people.

2021-04-22 03:03 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/CampaignSummary.java
> +            } else {
In the vast majority of cases they are. I've not, as per the overall description, finalized the dependent role, but am planning it being largely considered as support personnel.

2021-04-22 03:10 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/personnel/Person.java
> +        return (getPrimaryRole().isMechWarriorGrouping() || getPrimaryRole().isAerospacePilot()
I do for now, but will look at this specific example in the near future as I want to make the ransom values customizable.

2021-04-22 03:11 UTC, Windchild292 commented on MekHQ/src/mekhq/gui/CampaignGUI.java
>          int type = Integer.parseInt(evt.getActionCommand());
Missed this in removal.

2021-04-22 03:24 UTC, Windchild292 commented on MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> +                if ((person.getPrimaryRole().isTech() && role.isAstech())
It is probably a good idea, but I'll fully check tomorrow.

2021-04-23 11:42 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/CampaignSummary.java
> +            } else {
This is also consistent with their current implementation in MekHQ.

2021-04-23 12:52 UTC, Windchild292 commented on MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> +                if ((person.getPrimaryRole().isTech() && role.isAstech())
Folded it in, and expanded on a bunch of cases that both this and setPrimaryRole missed, plus removed the now useless setSecondaryRole checks

2021-04-23 12:53 UTC, Windchild292 commented
Ready for re-review @NickAragua.

2021-04-26 00:54 UTC, NickAragua approved these changes

2021-04-27 18:42 UTC, merged