AtB Dynamic Scenario: Fixing missing serialization on all non-map values
MegaMek/mekhq pull request #2915
Opened 2021-10-21 17:32 UTC by Windchild292

This fixes a save failure due to previously missing serialization on an uncompleted scenario, and adds serialization for all non-collections. I also organized the initialization and file I/O based on variable initialization, as I find it confusing to locate otherwise.

Currently botForceTemplates, botUnitTemplates, playerForceTemplates, playerUnitTemplates, scenarioModifiers are not serialized either, but I'm very much uncertain as to if this was intended or not and as such left that out.

Note: CI/CD will fail because of the current build failures.

2021-10-22 00:20 UTC, NickAragua requested changes
One request to move a comment back to where it was before. As I recall, those maps are only used during scenario force generation process and can be discarded afterwards.

2021-10-22 00:24 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
> +    // convenient pointers that let us keep data around that would otherwise need reloading
Ah, I assumed it was relating to the template, not the maps (was doing this over lunch).

Do the maps affect regenerating scenarios? If so... we probably should serialize them in future, and I can do so either immediately here or in another PR for 0.49.5 (your choice).

2021-10-22 00:26 UTC, NickAragua commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
> +    // convenient pointers that let us keep data around that would otherwise need reloading
I'll double check but I'm pretty sure they're only used while in the process of force generation.

2021-10-23 00:56 UTC, NickAragua approved these changes

2021-10-23 12:35 UTC, merged