Add functionality to Briefing Room/Add Scenario
MegaMek/mekhq pull request #3417
Opened 2022-08-01 19:39 UTC by sldfgunslinger2766

This PR adds the ability to impose flat C-Bill costs to New Missions created in the Briefing Room/Add Scenario Pane for use in Chaos Campaign style games using C-Bills. Changes to the JSpinner allow negative values to be applied in the Add Loot/Edit Loot to simulate costs for Missions that are debited to a Units finances by enabling the appropriate check box in the game resolution. Some minor verbiage changes were added in the Panes and Mission Reports to reflect the changes made.

2022-08-01 21:41 UTC, NickAragua requested changes
Reasonable idea, just needs a little cleanup.

2022-08-01 21:41 UTC, NickAragua commented on MekHQ/src/mekhq/campaign/mission/Loot.java
> +        if (cash.isNegative()) {
At this point, you might as well just remove the if blocks and always append cash.toAmountAndSymbolString() to desc (unless it's zero, I guess).

2022-08-01 23:13 UTC, sldfgunslinger2766 commented
Wouldn't removing the if blocks also remove the context of cost and payout as well? That is handy for clear record keeping in the reports.

2022-08-05 02:14 UTC, NickAragua approved these changes
Looking good.

2022-08-05 02:14 UTC, merged