individual units contribute to BV/unit count for opfor budget
MegaMek/mekhq pull request #3445
Opened 2022-09-05 00:49 UTC by NickAragua

Addresses an issue noticed during a CasualJoker stream where individual units assigned to dynamic scenarios weren't contributing to opfor BV/unit count budget.

2022-09-05 00:52 UTC, Windchild292 reviewed
Just missing some braces, otherwise this looks good

2022-09-05 00:52 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
> +            if (forceTemplate != null && forceTemplate.getContributesToBV()) {
```suggestion
            if ((forceTemplate != null) && forceTemplate.getContributesToBV()) {
```

2022-09-05 00:52 UTC, Windchild292 commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
> +            if (forceTemplate != null && forceTemplate.getContributesToBV()) {
```suggestion
            if ((forceTemplate != null) && forceTemplate.getContributesToBV()) {
```

2022-09-05 01:02 UTC, Windchild292 requested changes
The above plus the Code Scanning Issue needs to be fixed first

2022-09-05 03:09 UTC, NickAragua commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
> +        unitCount *= difficultyMultiplier;
I gotta say, this will result in a stupidly long line of code for what I'm trying to do.

2022-09-05 03:12 UTC, NickAragua commented on MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
> +        unitCount *= difficultyMultiplier;
Like, are we seriously considering that unitCount = (int) Math.floor((double) unitCount * difficultyMultiplier); is somehow better or easier to read than unitCount *= difficultyMultiplier?

2022-09-06 15:39 UTC, Windchild292 approved these changes

2022-09-06 15:39 UTC, merged