Childrens filter in personnel screen
MegaMek/mekhq pull request #3771
Opened 2023-10-24 10:14 UTC by nutritiousemployee

This is a simple added filter that shows any personnel whose age is lower than 13.
The aim is to have an easier way to sort out children without having to display the dates view, and order by birthdate.

The change for PersonnelFilter is in the filters list (row 80), and in the getFilteredInformation method. I had to pass the current date in the method as I couldn't find a way to retrieve that info from inside the method's switch.
The PersonnelTab only change should be on row 283, but the automated diff shows space changes in the whole file - not sure why as I'm using the suggested IDE settings.

Having changed getFilteredInformation there's two changes in PersonnelMarketDialog and RetirementDefectionDialog since they were calling the method as well. I believe these changes don't impact the functionality of the two classes.

2023-10-24 17:31 UTC, NickAragua requested changes
Looks good, just needs some whitespace changes for readability.

2023-10-24 17:31 UTC, NickAragua commented on MekHQ/src/mekhq/gui/PersonnelTab.java
> +        return filter.getFilteredInformation(entry.getModel().getPerson(entry.getIdentifier()),getCampaignGui().getCampaign().getLocalDate());
Style change request: spaces between parameters in parameter lists for readability.

2023-10-24 17:31 UTC, NickAragua commented on MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
> +                return nGroup.getFilteredInformation(entry.getModel().getPerson(entry.getIdentifier()),hqView.getCampaign().getLocalDate());
Style change request: spaces between parameters in parameter lists for readability.

2023-10-24 17:31 UTC, NickAragua commented on MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
> +                    return nGroup.getFilteredInformation(person,hqView.getCampaign().getLocalDate());
Style change request: spaces between parameters in parameter lists for readability.

2023-10-24 20:54 UTC, NickAragua requested changes
Sorry, one other thing - looks like you've changed all the tabs from 4 to 2 in PersonnelTab and PersonnelFilter, which we don't really want. Let's revert those, and then we'll be good to go.

2023-10-24 21:49 UTC, nutritiousemployee commented
This should be ready now.
There was also an extra space in PersonnelFilter for line 65 which I'm not sure if it was introduced by me by mistake or no, but it's gone either way

2023-10-25 02:47 UTC, NickAragua approved these changes
Looks good.

2023-10-25 14:07 UTC, merged