Fix 3839: load last save loads clientsettings.xml instead
MegaMek/mekhq pull request #3869
Opened 2024-03-07 07:59 UTC by Sleet01

Filter out `clientsettings.xml` when searching the user dir for the most recent MekHQ campaign save file.

Testing:
- Ran all 3 projects' unit tests
- Added unit tests for new FilenameFilter static member
- Tested with manually-created empty `clientsettings.xml` file alongside existing campaign saves.

Close #3839

2024-03-07 08:05 UTC, Sleet01 commented on MekHQ/unittests/mekhq/gui/panels/StartupScreenPanelTest.java
> +class StartupScreenPanelTest {
Github, do you not understand how unit tests work?  No.

2024-03-13 17:21 UTC, SJuliez requested changes
Functionally good, but please reformat the file filter

2024-03-13 17:21 UTC, SJuliez commented on MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
> +            accepted = (
Not sure what to make of this artsy formatting here. This could be written in two lines and "accepted" could be inlined.

2024-03-13 17:21 UTC, SJuliez commented on MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
> +            accepted = (
Speaking of lines 64++

2024-03-15 07:23 UTC, merged