Added Ability to Change Original Unit Assignment via Personnel Table
MegaMek/mekhq pull request #4146
Opened 2024-06-04 15:16 UTC by IllianiCBT

- Added the ability to reassign Original Unit to currently assigned unit via the personnel table mouse listener. If Person is not currently assigned to a Unit no change occurs.

- Added the ability to wipe Original Unit via the personnel table mouse listener.

Both of these allow users to reassign (or remove) original unit records en masse, rather than needing to do reassignments on an individual basis via the Edit Person dialog.

## Closes
Closes #4022

2024-06-04 15:23 UTC, IllianiCBT commented on MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> +        JMenuHelpers.addMenuIfNonEmpty(popup, menu);
I'm aware, but I don't want to have to rewrite the entire pop-up in this PR

2024-06-04 16:40 UTC, SJuliez requested changes
See comments

2024-06-04 16:40 UTC, SJuliez commented on MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> +            case CMD_ORIGINAL_TO_CURRENT: {
Those { are unnecessary

2024-06-04 16:40 UTC, SJuliez commented on MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> +                        person.setOriginalUnit(person.getUnit());
could re-use "unit", right?

2024-06-04 16:51 UTC, IllianiCBT commented
Requested revisions resolved

2024-06-06 15:15 UTC, SJuliez approved these changes

2024-06-06 15:15 UTC, merged