Implemented Random Mercenary Company Name Generator
MegaMek/mekhq pull request #4640
Opened 2024-08-15 11:46 UTC by IllianiCBT

This PR does a couple of things: predominately it implements a random name generator to generate a mercenary company name.

When a player starts a new campaign a random name will be generated in place of the previous 'My Campaign'. Additional company names can be generated via button in Campaign Options. New company names can be generated in active campaigns via the GM Tools dialog. This tech was needed for the upcoming Random Backgrounds Module, as we need to known the origin company name for characters with the 'Mercenary' origin.

Finally, whenever players have a contract against the Mercenary faction mhq will generate a random name for that enemy, instead of using faction name. This tech was needed for a future project currently in pre-development.

There are 6 types of random name: Corporate, Mercenary (Vanity type 1 and 2), Mercenary (Generic), and Pre-Fab (type 1 and 2). If a vanity name is generated mhq will use the name of the current campaign commander, if set, otherwise a random Callsign will be generated.

Examples of the kinds of names generated follows:

- Juggernaut's Centurions
- The Storm Outlaws
- Envision Associates
- Boomtube's Legends
- Raptor Investments
- Barnacle's Wolfpack Gunslingers
- Drillbit's Raven Tactical
- The Starfire Tempests
- Koschei's Midnight Marauders
- The Spectral Legionnaires
- Wallaby's Punchline Platoon
- The Stackpole Savages

2024-08-15 11:54 UTC, IllianiCBT commented on MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
> +    private MMButton createGenerateNameButton(JTextArea txtCompanyNamesGenerated) {
Resolved

2024-08-16 00:24 UTC, HammerGS commented on MekHQ/resources/mekhq/resources/RandomMercenaryCompanyNameGenerator.properties
> +EndWordMercenary.CONQUERORS.text=Conquerors
Cuirassier

2024-08-16 00:24 UTC, HammerGS commented on MekHQ/resources/mekhq/resources/RandomMercenaryCompanyNameGenerator.properties
> +EndWordMercenary.COMMANDERS.text=Commanders
Chevau-léger

2024-08-16 00:32 UTC, HammerGS requested changes
Tested and seems to work. Added some of the missing names we see for merc units. 

Also can this generated a numbered unit, i.e 21st Stormbringer Legion

2024-08-16 01:12 UTC, IllianiCBT commented
> Tested and seems to work. Added some of the missing names we see for merc units.
> 
> Also can this generated a numbered unit, i.e 21st Stormbringer Legion

It does now! :D

2024-08-16 01:13 UTC, IllianiCBT commented
Added numerical name prefixes, allowing us to generate names like "The 22nd Beef Brigade"

2024-08-16 02:18 UTC, HammerGS approved these changes

2024-08-16 02:19 UTC, merged

2024-08-16 02:27 UTC, HammerGS approved these changes
Tested and seems to work