Rolled Back Command Rights Scenario Modifiers
MegaMek/mekhq pull request #5223
Opened 2024-11-19 17:29 UTC by IllianiCBT

Rolled back the command right modifiers for House and Integrated contracts. They will now create forces similar to their pre-50.01 versions.

2024-11-19 17:46 UTC, Setsul commented
The ally weights in the contract difficulty estimate will need to be adjusted to match this.

2024-11-19 18:08 UTC, IllianiCBT commented
Ack! I made a mental note about that yesterday and then completely forgot it by this morning. Thanks for the catch. Any recommended values?

2024-11-19 18:12 UTC, IllianiCBT commented
Actually, I know exactly what I'll do

2024-11-19 18:21 UTC, IllianiCBT commented
The scope of this PR has changed. The title & description has been updated accordingly.

2024-11-19 18:24 UTC, Setsul commented
I see what you're going for.
You might still want to set the estimate ratios slightly higher than the guaranteed allied forces', since there are random scenario modifier that we still want to factor into the difficulty estimate a bit.
Liaison also probably also has to be adjusted downwards a bit, since we don't want that to have more of an effect on the difficulty estimate than House/Integrated.
Though to be honest, Liaison is highly dependent on the player's average number of unit and GBV per lance compared to a single unit within a certain weight range, so it's all guesswork without making that part of the method much more complex.

2024-11-19 18:28 UTC, IllianiCBT commented
Liaison is a big thorn in our side, one that I'm not entirely sure how to resolve cheaply.

My current thinking is that the difficulty estimate is 'good enough'. If you want to take another look at the values, though, I definitely wouldn't turn down the help. Especially as you seem to have a better grasp of maths than me :D

2024-11-19 18:41 UTC, Setsul commented
We're actually doing most of the work to do it properly already, it'll just be awkward to get the data since it's done in a different method. We can fairly easily figure out the average BV per player lance. What would need to be added is the logic get the average BV of an allied heavy/assault mek, but that's still easy enough.

I think the end goal should be to overhaul the difficulty estimate and make it factor in vehicles as well, but either way that's beyond the scope here.

Again, I'd call it good enough for now and look into again after scenario modifiers are settled a bit more. For a better estimate I'll also have to look into the chances of random modifiers that add allied forces.

2024-11-19 18:56 UTC, Setsul requested changes
I think you forgot to adjust the actual ratios and only changed the comments.

2024-11-19 19:09 UTC, IllianiCBT commented
Ugh, no, I'm just clearly one coffee short of a braincell this morning. Fixing

2024-11-23 20:43 UTC, HammerGS approved these changes

2024-11-23 20:43 UTC, merged