Implemented Nag Dialog Visual & Code Improvements
MegaMek/mekhq pull request #5522
Opened 2024-12-24 01:34 UTC by IllianiCBT

This PR rewrites our current nag dialogs to be a bit more visually interesting - for the player - and more feature robust - for us. Essentially I moved us from the `AbstractNagDialog` class to `JDialog`. This gives us access to a far wide suite of tools, when writing nag dialogs. Specifically when it comes to how we present information to the user.

Something we noticed a lot was players were being presented with these nags, without knowing how to address them. The 'you have no campaign commander' one was the most common culprit of this. Using the old nag dialogs we were very, very limited in how we could layout information as we were unable to easily use `html` formatting. By using `JDialog` that ceases to be an issue.

All together that means we go from this...
<img width="563" alt="image" src="https://github.com/user-attachments/assets/bfeb498b-02b8-499f-ba5f-c5c4ae988053" />

...to this...
<img width="650" alt="image" src="https://github.com/user-attachments/assets/9287352c-577b-488d-b0f1-75403034edce" />

Finally, from an internals perspective, I moved the nag dialog triggers out of `CampaignGUI.java` and into its own nag controller. This helps reduce the size of `CampaignGUI.java` and keeps all the nag functionality in one place.

2024-12-24 01:38 UTC, HammerGS commented
I have to stay the Commander, there is no Commander is odd wording. 

I think for that it should be just Please be advised...

2024-12-24 01:47 UTC, IllianiCBT commented
Done

2024-12-24 01:54 UTC, IllianiCBT commented
This PR partially addresses #5522

2024-12-26 02:31 UTC, NickAragua requested changes
This is really cool and adds a lot more immersion and "new user help". Other than a couple minor text suggestions, the main issue I have with it is the removal of unit tests, which I think we should retain in some form to avoid regression bugs in the future.

2024-12-26 02:31 UTC, NickAragua commented on MekHQ/resources/mekhq/resources/GUI.properties
> +  \ can choose to jettison your prisoners</i>
```suggestion
  \ can choose to jettison your prisoners.</i>
```

May also consider adding a :( to the end of the sentence, lol.

2024-12-26 02:31 UTC, NickAragua commented on MekHQ/resources/mekhq/resources/GUI.properties
> +  \ refuse non-critical contacts.</i>
```suggestion
  \ ignore non-critical contacts.</i>
```

2024-12-26 22:47 UTC, IllianiCBT commented
-sacrifices a turkey in the hopes the tests pass-

2024-12-26 22:55 UTC, IllianiCBT commented
Split the logic and gui elements of each nag into separate classes to more easily facilitate testing. As we test in an headless environment, here on GitHub, having gui elements in the testing causes no end of hassle. Separating the logic and testing that individually seemed like the best approach. It also has the added benefit of keeping everything nice and neatly self-contained.

2024-12-27 02:28 UTC, merged

2024-12-27 03:07 UTC, NickAragua commented
Thanks for restoring the unit tests, good stuff.